services:
  postgres-db:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  example-app:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      LISTEN_ADDRESS: "0.0.0.0:8080"
      POSTGRES_URL: "postgres://postgres:postgres@postgres-db:5432/postgres?sslmode=disable&pool_max_conns=10"
    depends_on:
      - postgres-db
