// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package authors

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID          string
	Name        string
	Description pgtype.Text
}

type Book struct {
	ID          string
	Name        string
	Description pgtype.Text
	AuthorID    string
	Rating      float64
	PublishedAt time.Time
}
